name: flutter_ebook
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  # sdk: ^3.7.0
  sdk: ^3.5.4
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  

  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  flutter_otp_text_field: ^1.4.0+2
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  flutter_bloc: ^9.0.0
  easy_localization: ^3.0.7+1
  flutter_localization: ^0.3.1
  url_launcher: ^6.3.1
  epub_view: ^3.2.0
  path_provider: ^2.1.5
  flutter_pdfview: ^1.4.0
  record: ^5.2.0
  just_audio: ^0.9.46
  path: ^1.9.0
  flutter_cached_pdfview: ^0.4.3
  sqflite: ^2.4.1
  # audio_waveforms: ^1.2.0
  http: ^0.13.6
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  # cache_audio_player_plus: ^1.1.0
  pdfx: ^2.8.0
  flutter_cache_manager: ^3.3.1
  animated_icon: ^0.0.6
  percent_indicator: ^4.2.4
  audioplayers: ^6.2.0
  # rive_common: ^0.4.15
  # rive_animated_icon: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  flutter_lints: ^5.0.0



flutter:

  
  
  
  uses-material-design: true

  
  
  assets:
    - assets/translations/
    - assets/images/
    - assets/books/burroughs-lost-continent.epub
    - assets/books/Shigoto_no_nihongo_IT_Gyoumuhen.pdf
    - assets/books/pdf.pdf
    - assets/icons/
    - assets/audios/
    - assets/audios/audio4.mp3

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
